import jackDanielsImg from '../assets/JackDaniels.png'
import jimBeamImg from '../assets/JimBeam.png'
import stalinskayaImg from '../assets/Stalinskaya.png'
import absoluteImg from '../assets/AbsoluteVodka.png'
import jaggerImg from '../assets/Jaggermeister.png'
import hennessyImg from '../assets/Hennessy.png'
import strongbowGold from '../assets/StrongbowApple.png'
import strongbowBerries from '../assets/StrongbowBerries.png'
import aviationGinImg from '..//assets/AviationGin.png'
import captainMorganImg from '../assets/CaptainMorgan.png'
import whiteWine from '../assets/WhiteWine.png'
import redWine from '../assets/RedWine.png'
import roseWine from '../assets/RoseWine.png'
import savoyRumImg from '../assets/SavoyRum.png'
import tequillaOlmecaImg from '../assets/TequillaOlmeca.png'
import AkashiImg from '../assets/Akashi.png'
import CedarRidgeImg from '../assets/CedarRidge.png'
import SheridanImg from '../assets/Sheridan.png'
import ChateauGloriaImg from '../assets/ChateauGloria.png'

let tohaniPricePerL = 13.2
let moldovaPricePerL = 15.7
let recasPricePerL = 17.1
let discountFor10L = 0.8 // %

let data = {
  products: [
    {
      id: 0,
      name: 'Captain Morgan',
      color: '',
      price: 59.99,
      type: 'Rum',
      volume: 0.7,
      quantity: 4,
      img: captainMorganImg,
      imgWidth: 140,
    },
    {
      id: 1,
      name: 'Stalinskaya',
      color: '',
      price: 29.99,
      type: 'Vodka',
      volume: 0.5,
      quantity: 6,
      img: stalinskayaImg,
      imgWidth: 130,
    },
    {
      id: 2,
      name: 'Jack Daniels',
      color: '',
      price: 79.97,
      type: 'Whiskey',
      volume: 0.7,
      quantity: 7,
      img: jackDanielsImg,
      imgWidth: 100,
    },
    {
      id: 3,
      name: 'Jim Beam',
      color: '',
      price: 69.97,
      type: 'Whiskey',
      volume: 0.7,
      quantity: 5,
      img: jimBeamImg,
      imgWidth: 120,
    },
    {
      id: 4,
      name: 'Absolute',
      color: '',
      price: 49.99,
      type: 'Vodka',
      volume: 0.7,
      quantity: 3,
      img: absoluteImg,
      imgWidth: 110,
    },
    {
      id: 5,
      name: 'Jaggermeister',
      color: '',
      price: 51.99,
      type: 'Liquor',
      volume: 0.7,
      quantity: 5,
      img: jaggerImg,
      imgWidth: 140,
    },
    {
      id: 6,
      name: 'Hennessy VS',
      color: '',
      price: 178.99,
      type: 'Cognac',
      volume: 0.7,
      quantity: 2,
      img: hennessyImg,
      imgWidth: 130,
    },
    {
      id: 7,
      name: 'Strongbow Gold',
      color: '',
      price: 3.5,
      type: 'Cider',
      volume: 0.33,
      quantity: 9,
      img: strongbowGold,
      imgWidth: 130,
    },
    {
      id: 8,
      name: 'Aviation',
      color: '',
      price: 129.99,
      type: 'Gin',
      volume: 0.7,
      quantity: 2,
      img: aviationGinImg,
      imgWidth: 130,
    },
    {
      id: 9,
      name: 'Strongbow Red',
      color: '',
      type: 'Cider',
      price: 3.99,
      volume: 0.33,
      quantity: 11,
      img: strongbowBerries,
      imgWidth: 130,
    },
    {
      id: 76,
      name: 'Savoy',
      color: '',
      type: 'Dark Rum',
      price: 39.99,
      volume: 0.7,
      quantity: 5,
      img: savoyRumImg,
      imgWidth: 130,
    },
    {
      id: 77,
      name: 'Olmeca Plata',
      color: '',
      type: 'whiskey',
      price: 89.99,
      volume: 0.5,
      quantity: 3,
      img: tequillaOlmecaImg,
      imgWidth: 140,
    },
    {
      id: 78,
      name: 'Akashi Meisei',
      color: '',
      type: 'Whiskey',
      price: 169.99,
      volume: 0.5,
      quantity: 2,
      img: AkashiImg,
      imgWidth: 130,
    },
    {
      id: 79,
      name: `Chateau Gloria`,
      color: '',
      type: 'Wine',
      price: 569.99,
      volume: 1,
      quantity: 1,
      img: ChateauGloriaImg,
      imgWidth: 140,
    },
    {
      id: 80,
      name: 'Cedar Ridge',
      color: '',
      type: 'Whiskey',
      price: 309.99,
      volume: 0.7,
      quantity: 3,
      img: CedarRidgeImg,
      imgWidth: 130,
    },
    {
      id: 81,
      name: `Sheridan's`,
      color: '',
      type: 'Whiskey',
      price: 99.99,
      volume: 1.25,
      quantity: 3,
      img: SheridanImg,
      imgWidth: 130,
    },
    {
      id: 10,
      name: 'Tohani',
      color: 'White',
      type: 'Sweet',
      price: tohaniPricePerL,
      volume: 1,
      quantity: 12,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 11,
      name: 'Tohani',
      color: 'White',
      type: 'Sweet',
      price: tohaniPricePerL * 2,
      volume: 2,
      quantity: 18,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 12,
      name: 'Tohani',
      color: 'White',
      type: 'Sweet',
      price: tohaniPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 5,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 13,
      name: 'Tohani',
      color: 'White',
      type: 'Semi-Sweet',
      price: tohaniPricePerL,
      volume: 1,
      quantity: 20,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 14,
      name: 'Tohani',
      color: 'White',
      type: 'Semi-Sweet',
      price: tohaniPricePerL * 2,
      volume: 2,
      quantity: 14,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 15,
      name: 'Tohani',
      color: 'White',
      type: 'Semi-Sweet',
      price: tohaniPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 6,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 16,
      name: 'Tohani',
      color: 'White',
      type: 'Semi-Dry',
      price: tohaniPricePerL,
      volume: 1,
      quantity: 19,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 17,
      name: 'Tohani',
      color: 'White',
      type: 'Semi-Dry',
      price: tohaniPricePerL * 2,
      volume: 2,
      quantity: 16,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 18,
      name: 'Tohani',
      color: 'White',
      type: 'Semi-Dry',
      price: tohaniPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 7,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 19,
      name: 'Tohani',
      color: 'Rose',
      type: 'Semi-Sweet',
      price: tohaniPricePerL,
      volume: 1,
      quantity: 16,
      img: roseWine,
      imgWidth: 70,
    },
    {
      id: 20,
      name: 'Tohani',
      color: 'Rose',
      type: 'Semi-Sweet',
      price: tohaniPricePerL * 2,
      volume: 2,
      quantity: 14,
      img: roseWine,
      imgWidth: 70,
    },
    {
      id: 21,
      name: 'Tohani',
      color: 'Rose',
      type: 'Semi-Sweet',
      price: tohaniPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 5,
      img: roseWine,
      imgWidth: 70,
    },
    {
      id: 22,
      name: 'Tohani',
      color: 'Rose',
      type: 'Semi-Dry',
      price: tohaniPricePerL,
      volume: 1,
      quantity: 12,
      img: roseWine,
      imgWidth: 70,
    },
    {
      id: 23,
      name: 'Tohani',
      color: 'Rose',
      type: 'Semi-Dry',
      price: tohaniPricePerL * 2,
      volume: 2,
      quantity: 10,
      img: roseWine,
      imgWidth: 70,
    },
    {
      id: 24,
      name: 'Tohani',
      color: 'Rose',
      type: 'Semi-Dry',
      price: tohaniPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 4,
      img: roseWine,
      imgWidth: 70,
    },
    {
      id: 25,
      name: 'Tohani',
      color: 'Red',
      type: 'Sweet',
      price: tohaniPricePerL,
      volume: 1,
      quantity: 20,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 26,
      name: 'Tohani',
      color: 'Red',
      type: 'Sweet',
      price: tohaniPricePerL * 2,
      volume: 2,
      quantity: 18,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 27,
      name: 'Tohani',
      color: 'Red',
      type: 'Sweet',
      price: tohaniPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 5,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 28,
      name: 'Tohani',
      color: 'Red',
      type: 'Semi-Sweet',
      price: tohaniPricePerL,
      volume: 1,
      quantity: 16,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 29,
      name: 'Tohani',
      color: 'Red',
      type: 'Semi-Sweet',
      price: tohaniPricePerL * 2,
      volume: 2,
      quantity: 12,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 30,
      name: 'Tohani',
      color: 'Red',
      type: 'Semi-Sweet',
      price: tohaniPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 4,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 31,
      name: 'Tohani',
      color: 'Red',
      type: 'Semi-Dry',
      price: tohaniPricePerL,
      volume: 1,
      quantity: 18,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 32,
      name: 'Tohani',
      color: 'Red',
      type: 'Semi-Dry',
      price: tohaniPricePerL * 2,
      volume: 2,
      quantity: 12,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 33,
      name: 'Tohani',
      color: 'Red',
      type: 'Semi-Dry',
      price: tohaniPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 4,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 34,
      name: 'Moldova',
      color: 'White',
      type: 'Sweet',
      price: moldovaPricePerL,
      volume: 1,
      quantity: 15,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 35,
      name: 'Moldova',
      color: 'White',
      type: 'Sweet',
      price: moldovaPricePerL * 2,
      volume: 2,
      quantity: 9,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 36,
      name: 'Moldova',
      color: 'White',
      type: 'Sweet',
      price: moldovaPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 3,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 37,
      name: 'Moldova',
      color: 'White',
      type: 'Semi-Sweet',
      price: moldovaPricePerL,
      volume: 1,
      quantity: 17,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 38,
      name: 'Moldova',
      color: 'White',
      type: 'Semi-Sweet',
      price: moldovaPricePerL * 2,
      volume: 2,
      quantity: 11,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 39,
      name: 'Moldova',
      color: 'White',
      type: 'Semi-Sweet',
      price: moldovaPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 4,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 40,
      name: 'Moldova',
      color: 'White',
      type: 'Semi-Dry',
      price: moldovaPricePerL,
      volume: 1,
      quantity: 12,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 41,
      name: 'Moldova',
      color: 'White',
      type: 'Semi-Dry',
      price: moldovaPricePerL,
      volume: 2,
      quantity: 8,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 42,
      name: 'Moldova',
      color: 'White',
      type: 'Semi-Dry',
      price: moldovaPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 5,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 43,
      name: 'Moldova',
      color: 'White',
      type: 'Dry',
      price: moldovaPricePerL,
      volume: 1,
      quantity: 14,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 44,
      name: 'Moldova',
      color: 'White',
      type: 'Dry',
      price: moldovaPricePerL * 2,
      volume: 2,
      quantity: 13,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 45,
      name: 'Moldova',
      color: 'White',
      type: 'Dry',
      price: moldovaPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 5,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 46,
      name: 'Moldova',
      color: 'Rose',
      type: 'Semi-Sweet',
      price: moldovaPricePerL,
      volume: 1,
      quantity: 15,
      img: roseWine,
      imgWidth: 70,
    },
    {
      id: 47,
      name: 'Moldova',
      color: 'Rose',
      type: 'Semi-Sweet',
      price: moldovaPricePerL * 2,
      volume: 2,
      quantity: 11,
      img: roseWine,
      imgWidth: 70,
    },
    {
      id: 48,
      name: 'Moldova',
      color: 'Rose',
      type: 'Semi-Sweet',
      price: moldovaPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 4,
      img: roseWine,
      imgWidth: 70,
    },
    {
      id: 49,
      name: 'Moldova',
      color: 'Rose',
      type: 'Semi-Dry',
      price: moldovaPricePerL,
      volume: 1,
      quantity: 14,
      img: roseWine,
      imgWidth: 70,
    },
    {
      id: 50,
      name: 'Moldova',
      color: 'Rose',
      type: 'Semi-Dry',
      price: moldovaPricePerL * 2,
      volume: 2,
      quantity: 12,
      img: roseWine,
      imgWidth: 70,
    },
    {
      id: 51,
      name: 'Moldova',
      color: 'Rose',
      type: 'Semi-Dry',
      price: moldovaPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 3,
      img: roseWine,
      imgWidth: 70,
    },
    {
      id: 52,
      name: 'Moldova',
      color: 'Rose',
      type: 'Dry',
      price: moldovaPricePerL,
      volume: 1,
      quantity: 13,
      img: roseWine,
      imgWidth: 70,
    },
    {
      id: 53,
      name: 'Moldova',
      color: 'Rose',
      type: 'Dry',
      price: moldovaPricePerL * 2,
      volume: 2,
      quantity: 9,
      img: roseWine,
      imgWidth: 70,
    },
    {
      id: 54,
      name: 'Moldova',
      color: 'Rose',
      type: 'Dry',
      price: moldovaPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 5,
      img: roseWine,
      imgWidth: 70,
    },
    {
      id: 55,
      name: 'Moldova',
      color: 'Red',
      type: 'Sweet',
      price: moldovaPricePerL,
      volume: 1,
      quantity: 10,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 56,
      name: 'Moldova',
      color: 'Red',
      type: 'Sweet',
      price: moldovaPricePerL * 2,
      volume: 2,
      quantity: 7,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 57,
      name: 'Moldova',
      color: 'Red',
      type: 'Sweet',
      price: moldovaPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 4,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 58,
      name: 'Moldova',
      color: 'Red',
      type: 'Semi-Sweet',
      price: moldovaPricePerL,
      volume: 1,
      quantity: 12,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 59,
      name: 'Moldova',
      color: 'Red',
      type: 'Semi-Sweet',
      price: moldovaPricePerL * 2,
      volume: 2,
      quantity: 10,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 60,
      name: 'Moldova',
      color: 'Red',
      type: 'Semi-Sweet',
      price: moldovaPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 6,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 61,
      name: 'Moldova',
      color: 'Red',
      type: 'Semi-Dry',
      price: moldovaPricePerL,
      volume: 1,
      quantity: 10,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 62,
      name: 'Moldova',
      color: 'Red',
      type: 'Semi-Dry',
      price: moldovaPricePerL * 2,
      volume: 2,
      quantity: 7,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 63,
      name: 'Moldova',
      color: 'Red',
      type: 'Semi-Dry',
      price: moldovaPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 3,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 64,
      name: 'Moldova',
      color: 'Red',
      type: 'Dry',
      price: moldovaPricePerL,
      volume: 1,
      quantity: 11,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 65,
      name: 'Moldova',
      color: 'Red',
      type: 'Dry',
      price: moldovaPricePerL * 2,
      volume: 2,
      quantity: 6,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 66,
      name: 'Moldova',
      color: 'Red',
      type: 'Dry',
      price: moldovaPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 2,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 67,
      name: 'Recas',
      color: 'White',
      type: 'Semi-Dry',
      price: recasPricePerL,
      volume: 1,
      quantity: 20,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 68,
      name: 'Recas',
      color: 'White',
      type: 'Semi-Dry',
      price: recasPricePerL * 2,
      volume: 2,
      quantity: 16,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 69,
      name: 'Recas',
      color: 'White',
      type: 'Semi-Dry',
      price: recasPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 8,
      img: whiteWine,
      imgWidth: 70,
    },
    {
      id: 70,
      name: 'Recas',
      color: 'Rose',
      type: 'Semi-Sweet',
      price: recasPricePerL,
      volume: 1,
      quantity: 22,
      img: roseWine,
      imgWidth: 70,
    },
    {
      id: 71,
      name: 'Recas',
      color: 'Rose',
      type: 'Semi-Sweet',
      price: recasPricePerL * 2,
      volume: 2,
      quantity: 16,
      img: roseWine,
      imgWidth: 70,
    },
    {
      id: 72,
      name: 'Recas',
      color: 'Rose',
      type: 'Semi-Sweet',
      price: recasPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 10,
      img: roseWine,
      imgWidth: 70,
    },
    {
      id: 73,
      name: 'Recas',
      color: 'Red',
      type: 'Semi-Dry',
      price: recasPricePerL,
      volume: 1,
      quantity: 18,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 74,
      name: 'Recas',
      color: 'Red',
      type: 'Semi-Dry',
      price: recasPricePerL * 2,
      volume: 2,
      quantity: 11,
      img: redWine,
      imgWidth: 70,
    },
    {
      id: 75,
      name: 'Recas',
      color: 'Red',
      type: 'Semi-Dry',
      price: recasPricePerL * 10 * discountFor10L,
      volume: 10,
      quantity: 8,
      img: redWine,
      imgWidth: 70,
    },
  ],
}

export default data
